# Generated by Django 4.1.3 on 2022-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='is_django',
            fields=[
                ('id', models.CharField(max_length=170, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=70)),
                ('lname', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('confirm_password', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
