# Generated by Django 4.1.3 on 2022-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='is_django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customId', models.CharField(default='', max_length=255)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('age', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
